#!/bin/bash
_ABOUT="Zhongwen Orthograpy"
_USAGE="Usage: zhoortho [-h] CHARACTERS..."
_DATAFILE="/usr/share/zhotools/zhoortho.sqlite"

if test -z "$1" -o "$1" == "-h" ; then
  echo "$_ABOUT"
  echo "$_USAGE"
  exit
else
  _INPUT=$1
fi

_CONDITION=""
for i in 1 2 3 4 ; do
  if test $i -gt ${#_INPUT} ; then
    break
  else
    _CONDITION+=" OR mistake = '${_INPUT:$((${#_INPUT}-$i))}'"
  fi
done
_CONDITION=${_CONDITION# OR }
sqlite3 -separator " " $_DATAFILE "SELECT * FROM ortho WHERE $_CONDITION ORDER BY LENGTH(mistake);"
