#!/bin/bash
_ABOUT="Zhongwen Orthograpy, GPL (c) Wei-Lun Chao <william.chao@ossii.com.tw>, 2011."
_USAGE="Usage: zhoortho [-h] CHARACTERS..."
_VERSION="0.1"
_DATAFILE="/usr/share/zhotools/zhoortho.ssv"

if test -z "$1" -o "$1" == "-h" ; then
  echo $_ABOUT
  echo $_USAGE
  exit
else
  _INPUT=$1
fi

_OUTPUTS=""
for i in 1 2 3 4 ; do
  if test $i -gt ${#_INPUT} ; then
    break
  else
    _BEGIN=$((${#_INPUT}-$i))
    _OUTPUT=`grep "^${_INPUT:$_BEGIN} " $_DATAFILE`
    _OUTPUTS+="\n$_OUTPUT"
  fi
done
echo -e "$_OUTPUTS" | grep -v '^$'
