#!/bin/bash
_ABOUT="Zhongwen Relate"
_USAGE="Usage: zhorelate [-h] CHARACTERS"
_DATAFILE="/usr/share/zhotools/zhorelate.sqlite"


if [ -z "$1" ] ;then   #輸入字為空
  echo "$_ABOUT"
  echo "$_USAGE"
  exit          
elif test "$1" == "-h" ; then
  echo "$_ABOUT"
  echo "$_USAGE"
  exit
fi

_SUMWORD=$*
_SUM=${#_SUMWORD}
_LN=$(($_SUM-1)) #總字數減一
_LNWORD=${_SUMWORD:$_LN}
if test "$_LNWORD" == "#" ; then
  exit
fi
_ALLWORD=`sqlite3 $_DATAFILE "SELECT fellows FROM relate WHERE leader = '$_LNWORD';"`
if [ -z "$_ALLWORD" ] ;then
  exit 1
fi

echo $_ALLWORD
