#!/bin/bash
_ABOUT="Zhongwen phonetic Transformation, GPL (c) Wei-Lun Chao <william.chao@ossii.com.tw>, 2010."
_USAGE="Usage: zhotrans [-h] [-t pinyin|braile] BOPOMOFO..."
_VERSION="0.2"
_DATAFILE="/usr/share/zhotools/zhotrans.ssv"

_TO="pinyin"
_INPUTS=""
while test "$1" ; do
  case "$1" in
    -h)
      echo "$_ABOUT"
      echo "$_USAGE"
      exit
      ;;
    -t)
      _TO="$2"
      shift
      shift
      ;;
    *)
      _INPUTS="$@"
      break
      ;;
  esac
done

_OUTPUTS=""
for _INPUT in $_INPUTS ; do
  if test $_TO == "braile" ; then
    _OUTPUT=`grep "^$_INPUT " $_DATAFILE | cut -d " " -f 3`
  else
    _OUTPUT=`grep "^$_INPUT " $_DATAFILE | cut -d " " -f 2`
  fi
  _OUTPUTS="$_OUTPUTS $_OUTPUT"
done
echo "$_OUTPUTS" | sed -e 's/^ //'
