#!/bin/bash
_ABOUT="Zhongwen phonetic Transformation"
_USAGE="Usage: zhotrans [-h] [-t pinyin|braile] BOPOMOFO..."
_DATAFILE="/usr/share/zhotools/zhotrans.sqlite"

_TO="pinyin"
_INPUTS=""
while test "$1" ; do
  case "$1" in
    -h)
      echo "$_ABOUT"
      echo "$_USAGE"
      exit
      ;;
    -t)
      _TO="$2"
      shift
      shift
      ;;
    *)
      _INPUTS="$@"
      break
      ;;
  esac
done

_CONDITION=""
if [ "$_TO" != "braile" ] ; then _TO="pinyin" ; fi
for _INPUT in $_INPUTS ; do
  _CONDITION+="SELECT $_TO FROM trans WHERE bopomofo = '$_INPUT'; "
done

echo $(sqlite3 $_DATAFILE "$_CONDITION")
